[project]
name = "oop-bank-account"
version = "0.1.0"
description = "simple OOP bank project"
authors = [
    {name = "prashanthiakka",email = "22wh1a6638@bvrithyderabad.edu.in"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

[tool.poetry]
packages = [{include = "oop_bank_account", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--cov=bank_account --cov-fail-under=90"

[tool.pylint]
disable = ["missing-module-docstring"]